---
title: "Links extras"
---



## Outros exemplos de R no jornalismo

- [O ano de 2020 no Spotify - Rodrigo Ortega](https://rpubs.com/ortegopolis/spotify2020)

- [Raspagem das estatísticas trimestrais da SSP - Gabriela Caesar](https://github.com/anacarolinamoreno/Curso-R-Globo/blob/master/R/aula-R_parte-2_raspagem_de_dados.R)

- [Raspagem de tabelas de violência contra mulher SSP - Gabriela Caesar](https://www.gabrielacaesar.com/2020/09/08/captura-de-dados-ssp-sp/)

- [Análise de dados eleitorais 2020 - Gabriela Caesar](https://github.com/gabrielacaesar/eleicoes2020)

- [Análise de dados sobre pessoas em posse de drogas - Cecília do Lago](https://www.estadao.com.br/infograficos/cidades,sem-lei-que-cite-quantidades-policia-da-destinos-diversos-a-flagrados-com-droga,977293)

- [Qual escola pública mehor alfabetiza crianças? - Cecília do Lago](https://www.estadao.com.br/infograficos/educacao,criancas-que-leem,1046679)

- [Tábata Amaral é tão governista quanto seu partido - Cecília do Lago](https://politica.estadao.com.br/noticias/geral,basometro-tabata-amaral-e-tao-governista-quanto-o-pdt,70002926170)



## Materiais de estudo

- [Intro to R for journalists: How to find great stories in data (inglês) com Andrew Ba Tran (Washington Post) R](https://journalismcourses.org/course/introtor/)


- Comunidade [R-Ladies São Paulo](https://www.instagram.com/rladiessaopaulo/) (veja uma breve [apresentação](https://r-ladies-sao-paulo.github.io/RLadiesTheme/))

- [Discourse - Fórum em português para tirar dúvidas sobre R](https://discourse.curso-r.com/)


- [Livro Ciência de Dados em R](https://livro.curso-r.com/), por Athos Damiani, Beatriz Milz, Caio Lente, Daniel Falbel, Fernando Correa, Julio Trecenti, Nicole Luduvice e William Amorim.


- [Curso-R](https://curso-r.com/) - Cursos, todo o [material didático está disponível gratuitamente](https://curso-r.com/material/).


- [Materiais de estudo sobre R](https://materiais-estudo-r.netlify.app/portugues.html) - Compilado de links úteis em Português
